### ISSUE TITLE
PotD RPR Notes

### ISSUE THREAD

**Issue by Enraa** [djcooke/compendium#1]
Hi! I just got my Necromancer clear on Enraa Aery (Leviathan) with Reaper. Attached are my notes on a Google Sheets copy for 151+ if it helps at all for the compendium. I also attached some fight specific notes for the bosses from 160 up to 190. https://docs.google.com/spreadsheets/d/1cV2F-cTgfeK_duY0pbkbZ_XTVNs_-J1S0VtUMtlDwf0/edit?usp=sharing

**Comment by djcooke** [comment]
This is fantastic, thanks! I'm a bit swamped right now, but will get this info into the site in a few days

**Comment by djcooke** [comment]
Got that all posted. You listed "Strength/Steel" in several places and I wasn't sure if you meant "and" or "or." I guessed on a case by case basis, so not 100% sure I got your intentions right. If you have a look and notice anything I got wrong, please let me know. Thanks again though for the excellent additions, and congrats on your clear! 🎉
