### ISSUE TITLE
POTD WAR 150 kill time with no offensive poms

### ISSUE THREAD

**Issue by Fenroe** [djcooke/compendium#2]
16-17 minutes with nothing whatsoever. Save Beserk and / or a full gauge to deal with the zombies.

**Comment by djcooke** [comment]
Ouch, sounds painful! Thanks for sharing. I'll list 17m as the kill time to be safe

**Comment by djcooke** [comment]
How would you like to be credited for this info? I usually include a preferred name and Discord tag, like `Person (Discord: Asdf#1234)`, but I can omit either or use a different format if you prefer

**Comment by Fenroe** [comment]
Hi. I'm not too bothered about credit but in any case just Fenroe without the discord tag would be great. Thanks for including this!

**Comment by djcooke** [comment]
Posted. Thanks again!
