### ISSUE TITLE
AST EO Boss Times

### ISSUE THREAD

**Issue by MochiFaa** [djcooke/compendium#57]
Hi!
I recently got my Omni Clear in EO and have some boss timers to share for AST. This was done in the most recent patch 6.51

if there is no specified time for STR (strength) or STL (steel) the duration was for the entire pull

Floor 10
01 - AST - 8m12 - STR
01 - AST - 7m27s - STR, 1m44s STL
01 - AST - 5m24s - 1 Grade 7 Tincture, STL, Unei

Floor 20
01 - AST - 4m43s - 4m08 STR, Unei, 4m43s Dreadbeast Heal Buff & STL
01 - AST - 9m33s - 2x Grade 7 Tinctures
01 - AST - 7m18s - STR, Dread Beast STL Buff

Floor 30
01 - AST - 6m40s - STR, STL, Unei
01 - AST - 5m01s - 3m40s Pox, STL, Doga

Floor 40
01 - AST - 7m21s - 2m11s STR, 5m23s STL
01 - AST - 6m8s - 2x Grade 7 Tinctures, STR, STL
01 - AST - 7m27s - 4m53s Dread Beast STR, 1x Grade 7 Tincture
01 - AST - 8m28s - 5m05 STL, 2x Grade 8 Tinctures

Floor 50
01 - AST - 8m38s - No Tinctures, 53s STR, STL
01 - AST - 6m46s to 7m - STR, 2x Grade 7 Tinctures
01 - AST - 7m02s - STR
01 - AST - 8m57s - No Poms, 2 Grade 8 Tinctures

Floor 60
01 - AST - 7m57s - Unei, STL
01 - AST - 12m53s - 3 Grade 8 Tinctures, 9m52s DreadSTR, 5m15s STR, 1m45s STL
01 - AST - 3m11s - Onion Knight, Full STR, Full STL
01 - AST - 5m18s - Doga, 1 Grade 8 Tincture

Floor 70
01 - AST - 6m46s - Doga, STL
02 - AST - 4m06s - Onion Knight, 1 Grade 8 Tincutre, 3m35s STR, Full STL, Full Dread Regen

Floor 80
01 - AST - 4m22s - Onion Knight, 3m27s STR, Full STL, 3m50 Pox
01 - AST - 4m35s - Onion Knight - no Poms/Tinctures

Floor 90
01 - AST - 4m36s - Onion Knight, 1m26s STR, Full STL, 1 Grade 8 Tincture
01 - AST - 6m39s - Doga, STR & STL, 2x Grade 8 Tinctures

Floor 99
01 - AST - 6m14s - 1 Grade 8 Tincture, STR & STL, 4x Dread Pomander Vulnstacks 3m08s, Onion Knight

if needed, I also have boss times noted for the following Jobs: 

- DRK
- SCH
- BLM
- BRD
- DNC
- MNK
- NIN
- SAM
- SGE

**Comment by djcooke** [comment]
Awesome, thanks! I will get these added. Do you know what level you were for the floor 10 kills?

**Comment by djcooke** [comment]
Also, can I credit you as MochiFaa in the changelog, or would you prefer something else?

**Comment by djcooke** [comment]
I've posted these with credit to MochiFaa since I haven't heard back. Please let me know if you'd like me to change that. Note that I rounded these up to safe estimates as I normally do. I'd gladly accept any timings you'd like to submit for other jobs too. Thanks again!
