### ISSUE TITLE
HOH Gorillas

### ISSUE THREAD

**Issue by Altia1234** [djcooke/compendium#75]
Hi, been a long time user of DD compendium as your site helps me getting lone hero and once and future queen! Just wanna report on a small error on HOH 81~90. 

The correct floor range for Gorillas (Heavenly Rowen) to show up is 81~84. [The site suggest it's 81 to 83 which might be wrong](https://www.ddcompendium.com/hoh_floorsets/081.html?enemy=0#enemies)

This might be wrong as 1. double checked with pillowyzeal's guide, and 2. I got this pic from friend who is doing HOH. The configuration in this pic will be impossible if Gorillas doesn't show up in 84, since that has a Shinzei and we all know Shinzei only start show up on 84.

![image](https://github.com/user-attachments/assets/07742eef-5769-465b-8d8b-dcf2154ce46b)

I am sorry I am very new to using github (since I don't code and I don't know how this place works) but I hope the submission helps! Thanks for the site, it really help a lot!

**Comment by djcooke** [comment]
Thanks for the info! I'll get that corrected shortly

**Comment by djcooke** [comment]
Can I credit you as "Altia1234" in the changelog, or would you prefer something else?

**Comment by djcooke** [comment]
Posted. Let me know if you'd like me to change the name, and thanks again!
