### ISSUE TITLE
Wrong agro type of some enemies in PotD

### ISSUE THREAD

**Issue by iVeigar** [djcooke/compendium#76]
According to this Google Doc [PotD QuickRef](https://docs.google.com/spreadsheets/d/1nKI0-AApj-aiuUimrPkuQUJaa4DU8Ox7KqdC_ibme8E/edit), documents listed below should be corrected: 

`_potd_001_enemies/dung_beetle.md` agro should be Proximity
`_potd_001_enemies/hippocerf.md` agro should be Proximity
`_potd_001_enemies/sprite.md` agro should be Sound
`_potd_041_enemies/persona.md` agro should be Proximity
`_potd_081_enemies/hapalit.md` agro should be Proximity

I've also verified the data in game.

p.s. There are mismatches in HoH and EO too, but I haven't verified them yet so I won't list here

**Comment by djcooke** [comment]
Thanks for reporting these! I've confirmed the first 3 and will take your word on the rest as I don't have time to run through them all at the moment. Can I credit you as iVeigar for the info, or is there a different name you'd prefer?

**Comment by djcooke** [comment]
Posted
