### ISSUE TITLE
Some HoH 91-100 corrections

### ISSUE THREAD

**Issue by Deeakron** [djcooke/compendium#81]
I recently ran through Heaven-on-High and noticed an error in the compendium with the floor range for the Heavenly Jinba; it says they only show up on floors 94-96 but I also encountered them on floor 97, as seen here:
![ffxiv_12262024_155103_990](https://github.com/user-attachments/assets/d6d4fb8c-9c61-4aad-8fc5-1440af71c7b3)

Also, in regards to whether or not Heavenly Shabti can be slept, they can, as seen here:
![ffxiv_12262024_155347_739](https://github.com/user-attachments/assets/560ba9d9-34ce-4f86-bd30-1b39d9e258b3)

Hopefully this information helps!

**Comment by djcooke** [comment]
I appreciate the info and will make those corrections, thanks! Can I credit you as Deeakron in the changelog, or is there a different name you'd prefer?

**Comment by djcooke** [comment]
Posted. Thanks again!
